services:
  user-service:
    build:
      context: .
      dockerfile: ./micro-services/user/Dockerfile
    environment:
      PORT: "7001"
    volumes:
      - ./data/ecommerce.db:/app/data/ecommerce.db
      - ./micro-services/user/migrations:/app/micro-services/user/migrations
    ports:
      - "7001:7001"

  product-service:
    build:
      context: .
      dockerfile: ./micro-services/product/Dockerfile
    environment:
      PORT: "7002"
    volumes:
      - ./data/ecommerce.db:/app/data/ecommerce.db
      - ./micro-services/product/migrations:/app/micro-services/product/migrations
    ports:
      - "7002:7002"

  order-service:
    build:
      context: .
      dockerfile: ./micro-services/order/Dockerfile
    environment:
      PORT: "7003"
    volumes:
      - ./data/ecommerce.db:/app/data/ecommerce.db
      - ./micro-services/order/migrations:/app/micro-services/order/migrations
    ports:
      - "7003:7003"

  shop-service:
    build:
      context: .
      dockerfile: ./micro-services/shop/Dockerfile
    environment:
      PORT: "7004"
    volumes:
      - ./data/ecommerce.db:/app/data/ecommerce.db
      - ./micro-services/shop/migrations:/app/micro-services/shop/migrations
    ports:
      - "7004:7004"

  warehouse-service:
    build:
      context: .
      dockerfile: ./micro-services/warehouse/Dockerfile
    environment:
      PORT: "7005"
    volumes:
      - ./data/ecommerce.db:/app/data/ecommerce.db
      - ./micro-services/warehouse/migrations:/app/micro-services/warehouse/migrations
    ports:
      - "7005:7005"
